# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: 목차
  items:
    - label: 'Creating docs'
      link: '/usage/creating-docs'
    - label: 'Navigation'
      link: '/usage/navigation'
    - label: 'Shadowing'
      link: '/usage/shadowing'
- label: Community
  items:
    - label: '카디 동아리 네이버 카페'
      link: https://cafe.naver.com/teamcadi
